06-03-2019  22:38:55,775 :  Graph E17 has 100 transitions
edge vertices are (22, 23, 24, 25, 26, 27)
	Altitude, Altitude, Angle
	Altitude, Altitude, CornerPoint
	Altitude, Altitude, LineSegment
	Altitude, Altitude, MidPoint
	Altitude, Angle, Altitude
	Altitude, Angle, HalfLine
	Altitude, Axis, HalfLine
	Altitude, CornerPoint, Altitude
	Altitude, HalfLine, Angle
	Altitude, HalfLine, Axis
	Altitude, HalfLine, LineSegment
	Altitude, LineSegment, Altitude
	Altitude, LineSegment, HalfLine
	Altitude, MidPoint, Altitude
	Angle, Altitude, Altitude
	Angle, Altitude, HalfLine
	Angle, Angle, Angle
	Angle, Angle, Axis
	Angle, Angle, CornerPoint
	Angle, Angle, LineSegment
	Angle, Angle, MidPoint
	Angle, Axis, Angle
	Angle, Axis, LineSegment
	Angle, CornerPoint, Angle
	Angle, CornerPoint, LineSegment
	Angle, HalfLine, Altitude
	Angle, HalfLine, HalfLine
	Angle, LineSegment, Angle
	Angle, LineSegment, Axis
	Angle, LineSegment, CornerPoint
	Angle, LineSegment, LineSegment
	Angle, LineSegment, MidPoint
	Angle, MidPoint, Angle
	Angle, MidPoint, LineSegment
	Axis, Altitude, HalfLine
	Axis, Angle, Angle
	Axis, Angle, LineSegment
	Axis, Axis, CornerPoint
	Axis, Axis, MidPoint
	Axis, CornerPoint, Axis
	Axis, HalfLine, Altitude
	Axis, LineSegment, Angle
	Axis, LineSegment, LineSegment
	Axis, MidPoint, Axis
	CornerPoint, Altitude, Altitude
	CornerPoint, Angle, Angle
	CornerPoint, Angle, LineSegment
	CornerPoint, Axis, Axis
	CornerPoint, CornerPoint, CornerPoint
	CornerPoint, CornerPoint, MidPoint
	CornerPoint, HalfLine, HalfLine
	CornerPoint, LineSegment, Angle
	CornerPoint, LineSegment, LineSegment
	CornerPoint, MidPoint, CornerPoint
	CornerPoint, MidPoint, MidPoint
	HalfLine, Altitude, Angle
	HalfLine, Altitude, Axis
	HalfLine, Altitude, LineSegment
	HalfLine, Angle, Altitude
	HalfLine, Angle, HalfLine
	HalfLine, Axis, Altitude
	HalfLine, CornerPoint, HalfLine
	HalfLine, HalfLine, Angle
	HalfLine, HalfLine, CornerPoint
	HalfLine, HalfLine, LineSegment
	HalfLine, HalfLine, MidPoint
	HalfLine, LineSegment, Altitude
	HalfLine, LineSegment, HalfLine
	HalfLine, MidPoint, HalfLine
	LineSegment, Altitude, Altitude
	LineSegment, Altitude, HalfLine
	LineSegment, Angle, Angle
	LineSegment, Angle, Axis
	LineSegment, Angle, CornerPoint
	LineSegment, Angle, LineSegment
	LineSegment, Angle, MidPoint
	LineSegment, Axis, Angle
	LineSegment, Axis, LineSegment
	LineSegment, CornerPoint, Angle
	LineSegment, CornerPoint, LineSegment
	LineSegment, HalfLine, Altitude
	LineSegment, HalfLine, HalfLine
	LineSegment, LineSegment, Angle
	LineSegment, LineSegment, Axis
	LineSegment, LineSegment, CornerPoint
	LineSegment, LineSegment, LineSegment
	LineSegment, LineSegment, MidPoint
	LineSegment, MidPoint, Angle
	LineSegment, MidPoint, LineSegment
	MidPoint, Altitude, Altitude
	MidPoint, Angle, Angle
	MidPoint, Angle, LineSegment
	MidPoint, Axis, Axis
	MidPoint, CornerPoint, CornerPoint
	MidPoint, CornerPoint, MidPoint
	MidPoint, HalfLine, HalfLine
	MidPoint, LineSegment, Angle
	MidPoint, LineSegment, LineSegment
	MidPoint, MidPoint, CornerPoint
	MidPoint, MidPoint, MidPoint

